### ISSUE TITLE
Missing field id

### ISSUE THREAD

**Issue by josejachuf** [pepoviola/tide-basic-crud#11]
Hi, I'm learning Tide Following your tutorial It is helping me a lot 

Now, I'm in https://javierviola.com/post/03-basic-crud-with-rust-using-tide-move-to-db/ 

If you do not spend an **id** from the client, it returns an error that does not have a valid **id** 

in:

```
 async fn create(mut req: Request<State>) -> tide::Result {
        let dino: Dino = req.body_json().await?;
        // dino.id = Uuid::new_v4();
        let db_pool = req.state().db_pool.clone();
        let row = query_as!(
            Dino,
            r#"
            INSERT INTO dinos (id, name, weight, diet) VALUES
            ($1, $2, $3, $4) returning id, name, weight, diet
            "#,
            dino.id,            
            dino.name,
            dino.weight,
            dino.diet
        )
        .fetch_one(&db_pool)
        .await?;

        let mut res = Response::new(201);
        res.set_body(Body::from_json(&row)?);
        Ok(res)
    }
```
I try 

`Uuid::new_v4() 
`
instead 

`dino.id`

but without success

**Comment by pepoviola** [comment]
Hi @josejachuf, thanks for read my blog and I happy that help you. I review the code and the issue there is generated when serde try to deserialize the payload into the the `Dino` struct. To allow to **not** send the `id` from the client you need to apply this changes:

```diff
--- a/src/main.rs
+++ b/src/main.rs
@@ -30,6 +30,7 @@ pub struct State {

 #[derive(Debug, Clone, Deserialize, Serialize)]
 pub struct Dino {
+    #[serde(default = "Uuid::new_v4")]
     id: Uuid,
     name: String,
     weight: i32,
```

With this field attribute (https://serde.rs/field-attrs.html) we define the function to set the `id` if not provided in the payload.

---

I will update the code and the blog to use this fix 👍 

Thanks again for read me and glad to help you.

**Comment by josejachuf** [comment]
Thanks a lot. Today I will look at this

**Comment by josejachuf** [comment]
This works fine!
