### ISSUE TITLE
update sqlx from 0.3 to 0.5

### ISSUE THREAD

**Issue by josejachuf** [pepoviola/tide-basic-crud#12]
When you update the SQLX version from 0.3 to 0.5

First I changed
` Pool::new(&db_url).await.unwrap()`

for

` Pool::connect(&db_url).await.unwrap()`

Then, this error occurs: 

> error: one of the features ['runtime-actix-native-tls', 'runtime-async-std-native-tls', 'runtime-tokio-native-tls', 'runtime-actix-rustls', 'runtime-async-std-rustls', 'runtime-tokio-rustls'] must be enabled
>   --> /home/jose/.cargo/registry/src/github.com-1ecc6299db9ec823/sqlx-rt-0.5.10/src/lib.rs:9:1
>    |
> 9  | / compile_error!(
> 10 | |     "one of the features ['runtime-actix-native-tls', 'runtime-async-std-native-tls', \
> 11 | |      'runtime-tokio-native-tls', 'runtime-actix-rustls', 'runtime-async-std-rustls', \
> 12 | |      'runtime-tokio-rustls'] must be enabled"
> 13 | | );
>    | |_^
> 
> error: could not compile `sqlx-rt` due to previous error
> warning: build failed, waiting for other jobs to finish...
> error: build failed
> 

I understand that I have to add **runtime-async-std-rustls**, as it explains here [1]. By adding it, the aforementioned error is solved, but others appear:

In all **query_as!**

> 
> let row = query_as!(
>    |  _______________^
> ...    
>    | |_____^ expected `i32`, found enum `std::option::Option`
> 

>  let row = query_as!(
>    |  _______________^
> ...
> 57 | |     )
>    | |_____^ expected struct `std::string::String`, found enum `std::option::Option`
>    |
>    = note: expected struct `std::string::String`
>                 found enum `std::option::Option<std::string::String>`
>    = note: this error originates in the macro `$crate::sqlx_macros::expand_query` (in Nightly builds, run with -Z macro-backtrace for more info)
> 

Please, I could give me any help with this 
Thanks

Jose

[1] https://javierviola.com/post/06-basic-crud-with-rust-using-tide-final-refactor-and-complete-ci-cd/

**Comment by josejachuf** [comment]
I was reading this [1] I could solve it, but I do not understand what happens.

I had to do for each field, regardless of the same type:

`my-field as "my-field!" `

I am using another table and other fields, but for your example it would be this: 

```
INSERT INTO dinos (id, name, weight, diet, user_id) VALUES
        ($1, $2, $3, $4, $5) returning 
         id as "id!", 
         name as "name!", 
         weight as "weight!", 
         diet as "diet!", 
         user_id as "user_id!"
```

Is there a better way to do this? 

[1] https://docs.rs/sqlx/0.5.10/sqlx/macro.query_as.html#troubleshooting-error-mismatched-types

**Comment by pepoviola** [comment]
Hi @josejachuf, that is mostly because the fields in the table accept NULL, I need to update the schema in the post since the code assume those have the NOT NULL contraint. I will try to review and update asap.

Thanks!!

**Comment by josejachuf** [comment]
I understand the point @pepoviola. On my table, only one field accept NULL, however I had to make the modification [**my-field as "my-field!"**]  for all fields.
