### ISSUE TITLE
 ERROR [cacher 5/5] RUN cargo chef cook --release --recipe-path recipe.json

### ISSUE THREAD

**Issue by mofeng-me** [pepoviola/tide-basic-crud#8]
#17 42.65 error[E0658]: use of unstable library feature 'renamed_spin_loop'
#17 42.65   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/spinning_top-0.2.4/src/spinlock.rs:57:17
#17 42.65    |
#17 42.65 57 |                 hint::spin_loop();
#17 42.65    |                 ^^^^^^^^^^^^^^^
#17 42.65    |
#17 42.65    = note: see issue #55002 <https://github.com/rust-lang/rust/issues/55002> for more information
#17 42.65
#17 42.65 error: aborting due to previous error
#17 42.65
#17 42.65 For more information about this error, try `rustc --explain E0658`.
#17 42.66 error: could not compile `spinning_top`
#17 42.66
#17 42.66 To learn more, run the command again with --verbose.
#17 42.66 warning: build failed, waiting for other jobs to finish...
#17 43.54 error: build failed
#17 43.55 thread 'main' panicked at 'Exited with status code: 101', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.20/src/recipe.rs:131:27
#17 43.55 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by pepoviola** [comment]
Hi @mofengme, thanks for report. I will check asap.
Thx!

**Comment by pepoviola** [comment]
Hi @mofengme, should be fixed in the `main` branch now, thanks!

**Comment by mofeng-me** [comment]
@pepoviola pe  Docker image has built success!  But an error below  when  `docker run ` 

```
./tide-basic-crud: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory
```

**Comment by pepoviola** [comment]
Hi @mofengme, thanks again for reporting. I added the missing dep to the `runtime`. Should work as expected now.

Thx!

**Comment by pepoviola** [comment]
Closing now, let me know if you find any other issue. 
Thanks!
